### ISSUE TITLE
Add automatization to deploy repo on PyPI

### ISSUE THREAD

**Issue by AlekseySh** [OML-Team/open-metric-learning#171]

**Comment by AlekseySh** [comment]
here are some developments
```
name: Push to PyPI

on:
  push:
    tag:
      - release.*


jobs:
  publish_on_pypi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Exit if not on main branch
      if: endsWith(github.ref, 'main') == false
      run: exit 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8.0"

    - name: Build wheel
      run: |
        make build_wheel

    - name: Push the distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        repository_url: https://upload.pypi.org/legacy/
        skip_existing: true


  test_installation_from_pypi:
    runs-on: ubuntu-latest
    needs: publish_on_pypi
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Exit if not on main branch
      if: endsWith(github.ref, 'main') == false
      run: exit 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8.0"

    - name: Installation
      run: |
        make pip_install_actual_oml
        python3 -c "from oml.losses.triplet import TripletLoss"

```

**Comment by Illumaria** [comment]
Wouldn't this action be preferred for releases only, or do still you want to have it for tags?

**Comment by AlekseySh** [comment]
@Illumaria , The idea is the following: if someone adds a `release` tag to the main branch, GitHub Actions pushes it to PyPI

**Comment by Illumaria** [comment]
Yes, that much I understand. Sorry, I must have been unclear. I mean, you could probably benefit more from using `on: release` instead of `on: push`. It will trigger the workflow execution when a [release](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases) is published via the GitHub UI. When you publish a release on GitHub, it tags the target (e.g. `main`) branch with a specific version of the release. Each execution of the workflow is therefore guaranteed to be a tagged commit on the target branch.

In case you are not going to use the GitHub Releases functionality, then yes, filtering workflow trigger events by branch and tag is the way to go. In this case, what is the exact pattern of tags that you want to use? You probably won't have the same `release` tag for every version. So will it look like `release.v0.3.4`, `release.0.3.4`, `v0.3.4` (the most common option), `0.3.4`, or something else?

**Comment by AlekseySh** [comment]
We don't use GitHub UI for publishing, but we will consider this option, thanks.

As for the second question, I thought about this schema: `release.0.3.4`.

**Comment by Illumaria** [comment]
Ooookay. I've never worked very close to release flows, and this is one of the main reasons why I got interested in this task. I now would like to share the results of my research, at least to make sure we're on the same page. 😀

First of all, it is worth noting that the phrase
> if someone adds a `release` tag to the main branch

is technically incorrect. The tag is assigned to a _commit_, not a _branch_. This means that if some tagged commit is present in many branches, ~~we can't tell~~ there's no point in specifying the branch that the tag was assigned on. All these branches fit. If we still want to stick to the `main` branch here, the best we can do is to check that the tagged commit is present in the `main` branch commit history. This is implemented in the snipped provided below.

Another important thing to mention is that if at some point you decide to tag some old commit, the workflow won't be triggered. It is designed to be like this, and the explanation can be found [here](https://github.com/orgs/community/discussions/25963).

Here is the resulting workflow config. I tested it with publishing to Test PyPI, so it's most likely to be ready to use as is, provided that you had specified your token in the repository Secrets.

```yaml
name: Publish to PyPI

on:
  push:
    tags:
      - release.*

jobs:
  check_tag_status:
    name: Check if the tag is in the main branch commit history
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if the tag is in the main branch commit history
        run: |
          git merge-base --is-ancestor ${{ github.ref }} remotes/origin/main

  build_and_publish_to_pypi:
    name: Build and publish Python distribution to PyPI
    needs: check_tag_status
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8.0"

    - name: Build a binary wheel
      run: |
        make build_wheel

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}

  test_installation_from_pypi:
    needs: build_and_publish_to_pypi
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8.0"

    - name: Install and import open-metric-learning package
      run: |
        make pip_install_actual_oml
        python3 -c "from oml.losses.triplet import TripletLoss"
```

**Comment by AlekseySh** [comment]
@Illumaria thank you for the research and for the provided code. 

There is one problem (that already was in my draft for the YAML file). The problem is that PyPI requires some time to update its state. So, if you try to install the latest version of the repo from PyPI just after you push it, PyPI returns you an error that this version does not exist. I thought about using a timer or scheduler for doing the installation, but then I realized that we can simply remove the whole step since it basically tests that PyPI did everything correctly (but I guess we can just trust it).

So, my point is: let's remove `test_installation_from_pypi`

**Comment by AlekseySh** [comment]
And there is one more request to the workflow: could you realize how to call it only after all the rest workflows?
We don't push the repo to PyPI and a few minutes later realize that some of the tests become red.

**Comment by Illumaria** [comment]
> So, my point is: let's remove `test_installation_from_pypi`

Agreed. I only added it because it was in your initial config. 😅 I personally thought that `passed tests` + `successful publish to PyPI` should be enough.

> And there is one more request to the workflow: could you realize how to call it only after all the rest workflows?
We don't push the repo to PyPI and a few minutes later realize that some of the tests become red.

This is technically easy, but in case with tags it doesn't seem logical. Keeping in mind that we can only tag a specific commit, you wouldn't want to tag a random commit as a release one before you make sure it passes all the tests, would you? So the pipeline should probably look like this:
1. Implement some feature/make a fix.
2. Make a PR and run all workflows with tests.
3. Merge the PR.
4. Tag the merge commit (locally, since you said you are not going to use GitHub UI) on the `main` branch and push that tag.

So by the time the new feature/fix reaches the `main` branch, the commit you are going to tag is already fully tested. 🤔

**Comment by AlekseySh** [comment]
@Illumaria I see the sequence like this (the first 3 points are the same):

1. Implement some feature/make a fix in a separate branch.
2. Create a PR that would trigger all workflows with tests.
3. Merge the PR.
4. Go to the main branch, change the version in `oml/__init__.py`, tag the commit as a release commit, and push it.
5. CI runs workflow. Since the commit is tagged, it also pushes the repo to PyPI. 

At stage 5 we normally assume that everything was tested at stage 2.
The problem is that even if it's true, something (especially external) could change since that time. Probably we cannot download checkpoints anymore or something like this. So, on stage 5 it would be great to run tests first and only push the repo to PyPI after on.

**Comment by AlekseySh** [comment]
As far as I understand, you suggest tagging an already merged commit to guarantee that tests are okay. Hm. It also makes sense but I don't like one minor thing: Imagine, I updated the version of the library and merged that commit to the main branch. Then I forgot to tag the merge commit. So, we have an inconsistency between versions in PyPI and versions in GitHub. It's minor, but still worth mentioning.

**Comment by AlekseySh** [comment]
@Illumaria I did not know that we can push a tag to the commit after we merged it. If so, your suggestion makes sense. Whether we can push a tag to some specific commit in branch history or only to HEAD?

**Comment by Illumaria** [comment]
> Whether we can push a tag to some specific commit in branch history or only to HEAD?

The tag can be assigned to any commit in history. But please keep in mind that the workflow will only be triggered if the tagged commit has the corresponding workflow config. For example, consider the following commit history:
`A ---> B ---> C (workflow implemented) ---> D ---> E (HEAD)`,
where the workflow (triggered by `on: push: tags` event) was implemented in commit `C`. You can tag any of the commits from `A` to `E`, but the workflow will only be triggered for the commits `C` to `E`.

**Comment by AlekseySh** [comment]
@Illumaria Got it, it sounds logical.

**Comment by AlekseySh** [comment]
@Illumaria I thought that the problem was we have no `GITHUB_TOKEN` in our GitHub secrets. I created a new token in my personal GitHub account and tried to add it to the secrets, but it says that the secret name cannot start with `GITHUB`. Seems like it's a special type of secrets.

**Comment by Illumaria** [comment]
Yeah, you don't need to (and actually cannot) specify your `GITHUB_TOKEN` explicitly. It seems like you have restricted permissions for the repo Actions (Settings -> Actions -> General -> Workflow permissions). Just compare the logged permissions for the job in [my fork](https://github.com/Illumaria/open-metric-learning/actions/runs/3600021660/jobs/6064227683#step:1:16) and in [this repo](https://github.com/OML-Team/open-metric-learning/actions/runs/3600955943/jobs/6066196955#step:1:16).

**Comment by AlekseySh** [comment]
@Illumaria I just pushed the new version of OML to the main branch. Let's see what's gonna happen

**Comment by AlekseySh** [comment]
@Illumaria Tests were green, but the publishing procedure was skipped by some unclear reason: https://github.com/OML-Team/open-metric-learning/actions/runs/3601872903

**Comment by Illumaria** [comment]
The reason is the same: the `autotag` job made an attempt to create a tag but was [unable](https://github.com/OML-Team/open-metric-learning/actions/runs/3601872903/jobs/6068173395#step:4:14) to do so due to lack of permission.

**Comment by AlekseySh** [comment]
<img width="837" alt="Screenshot 2022-12-02 at 15 19 08" src="https://user-images.githubusercontent.com/20143575/205313367-de375d83-b12a-4096-b883-097b5ccaa131.png">

**Comment by AlekseySh** [comment]
@Illumaria I cannot select the first option. I picked the last one and run the publishing job one more time (just in case), it did not help.

**Comment by Illumaria** [comment]
@AlekseySh Can you please check the organization settings? As explained [here](https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization#configuring-the-default-github_token-permissions):

>  By default, when you create a new organization, `GITHUB_TOKEN` only has read access for the `contents` scope.

And [here](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#how-the-permissions-are-calculated-for-a-workflow-job):

> The permissions for the `GITHUB_TOKEN` are initially set to the default setting for the enterprise, organization, or repository.

I believe we have two ways of fixing it:
1. Enable write access in organization and then repository settings.
2. If you don't want to enable that access on org/repo scale, we can try to tweak the job permissions like this:
    ```yaml
    jobs:
      autotag:
        permissions: write-all
    ...
    ```
