### ISSUE TITLE
The problem with `TripletMinerWithMemory` when `expand_k` > 1

### ISSUE THREAD

**Issue by PapaMadeleine2022** [OML-Team/open-metric-learning#349]
Hello, when validating, it always show error:

```
Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.
```

How fix it?

**Comment by AlekseySh** [comment]
Could you provide more details, please? 

For example, do you run the existing validation pipeline or you work in python? 
And more lines of error trace, please.

**Comment by PapaMadeleine2022** [comment]
@AlekseySh I don't know what the specific reason is. At first I thought the reason is caused by my large validation dataset(5000x5000 size). But I find that the error shows when validating every time when I use `triplets_with_memory` for `miner`.

**Comment by AlekseySh** [comment]
5k x 5k is fine. 

Could you provide parameter values for your miner?

**Comment by PapaMadeleine2022** [comment]
> 5k x 5k is fine.
> 
> Could you provide parameter values for your miner?

criterion:
  name: triplet_with_miner
  args:
    need_logs: True
    margin: null
    reduction: mean
    miner:
      name: triplets_with_memory
      args:
        bank_size_in_batches: 50
        tri_expand_k: 3

**Comment by PapaMadeleine2022** [comment]
> Do you observe this error only with this miner? Do you run code via `train.py` (from examples) and config?
Yes, I run code via `train.py` (from examples) and config.
Besides, when I change to use:
```
criterion:
  name: triplet_with_miner
  args:
    need_logs: True
    margin: 0.15
    reduction: mean
    miner:
      name: hard_triplets
      args: {}
```
or
```
criterion:
  name: triplet_with_miner
  args:
    need_logs: True
    margin: 0.15
    reduction: mean
    miner:
      name: hard_triplets
      args: {}
```
```
criterion:
  name: triplet_with_miner
  args:
    need_logs: True
    margin: null
    reduction: mean
    miner:
      name: all_triplets
      args: {}
```
the error would show.
