### ISSUE TITLE
How to use other lr strategy like cosine ?

### ISSUE THREAD

**Issue by PapaMadeleine2022** [OML-Team/open-metric-learning#356]
I find the `lr` is consistent in all examples, like [lr: 1e-5](https://github.com/OML-Team/open-metric-learning/blob/release.0.3.14/examples/extractor_cub/train_cub.yaml#L72). Can you give a example about  how to use other `lr` strategy like `cosine` ?

**Comment by AlekseySh** [comment]
@PapaMadeleine2022 because it has been merged to main yesterday :) 

There is a row in table regarding scheduling, exactly what you want:
https://github.com/OML-Team/open-metric-learning/tree/main/pipelines/features_extraction

**Comment by PapaMadeleine2022** [comment]
Thank you. Now I can use the `cosine` lr strategy
by using configs:

```
optimizer:
  name: adam
  args:
    lr: 1e-5  # if you provide scheduler this parameter will be ignored

scheduling: 
    scheduler_interval: epoch
    scheduler_frequency: 1
    scheduler: 
        name: cosine_annealing
        args:
          T_max: 100
```
