### ISSUE TITLE
Questions about parameter `n_instances`

### ISSUE THREAD

**Issue by PapaMadeleine2022** [OML-Team/open-metric-learning#370]
Hello, in `pipelines/features_extraction/extractor_cub/train_cub.yaml`, the default configs about `sampler` are:

```
sampler:
  name: balance
  args:
    n_labels: 8
    n_instances: 4
```
I have two questions:
1: If one `label` class has only 2 instances, no more than 4 instances,  what `oml` will do? Discard this `label` class ?
2: Will the effect be better if we change the value of `n_instances` to larger ?
