### ISSUE TITLE
When to use `augs_albu` or `augs_hypvit_torch` ? 

### ISSUE THREAD

**Issue by PapaMadeleine2022** [OML-Team/open-metric-learning#371]
As we can see, in the `pipelines/features_extraction/extractor_cub/train_cub.yaml`, the `transforms` is `augs_albu` like:
```
transforms_train:
  name: augs_albu
  args:
    im_size: 224

transforms_val:
  name: norm_resize_albu
  args:
    im_size: 224
```

in the `pipelines/features_extraction/extractor_sop/train_sop.yaml`, the `transforms` is `augs_hypvit_torch` like:
```
transforms_train:
  name: augs_hypvit_torch
  args:
    im_size: 224

transforms_val:
  name: norm_resize_hypvit_torch
  args:
    im_size: 224
    crop_size: 224
```
I use respectively `augs_albu` and `augs_hypvit_torch` to train my normal dataset, there is a large gap in precision.  Using `augs_albu` has higher precision than `augs_hypvit_torch`. So I wonder when to properly use `augs_albu` or `augs_hypvit_torch` for better effect?
