### ISSUE TITLE
Switch a mining strategy during training

### ISSUE THREAD

**Issue by Fissium** [OML-Team/open-metric-learning#446]
Hi. Is it possible to switch a mining strategy during training, for example, from `all_triplets` to `hard_triplets` after several epochs?
My problem is that when training with a large batch size:
```yml
sampler:
  name: category_balance
  args:
    n_labels: 32
    n_instances: 5
    n_categories: 6
    resample_labels: True
    weight_categories: True
```

and the following config:
```yml
criterion:
  name: triplet_with_miner
  args:
    need_logs: True
    margin: 0.15
    reduction: mean
    miner:
      name: hard_triplets
      args: {}
```
triplet loss stuck at the margin value.

With a lower batch size the loss doesn't stack:
```yml
sampler:
  name: category_balance
  args:
    n_labels: 12
    n_instances: 3
    n_categories: 3
    resample_labels: True
    weight_categories: True
```
I have for about 100k classes in a dataset.
