### ISSUE TITLE
How to make model better?

### ISSUE THREAD

**Issue by PapaMadeleine2022** [OML-Team/open-metric-learning#495]
I have trained model by `Contrastive ones`, like [TripletLoss](https://open-metric-learning.readthedocs.io/en/latest/contents/losses.html#tripletlosswithminer).But how to make model better ? 
Generally, first we can train model  by `Classification ones` , like `ArcFace`. then we finetune the last embedding layer by `Contrastive ones`.

Do you have any ideas?

**Comment by AlekseySh** [comment]
I need more details: your task setup; dataset set size (num labels, num images...), what are the current metrics? And it would also be useful to visualize your predictions (like [here](https://github.com/OML-Team/open-metric-learning/blob/main/pipelines/features_extraction/visualization.ipynb))

**Comment by PapaMadeleine2022** [comment]
I use the `[train_cub.yaml](http://10.168.105.252:8412/edit/metric-learning/open-metric-learning-release.0.4.0/pipelines/features_extraction/extractor_zhufulu/train_cub.yaml)`  to train my model.

num labels: 2623
num images: 78397

metrics:
```
metric_args:
  metrics_to_exclude_from_visualization: [cmc,]
  cmc_top_k: [1]
  map_top_k: [5]
  fmr_vals: [0.01]
  pfc_variance: [0.5, 0.9, 0.99]
  return_only_overall_category: True
  visualize_only_overall_category: True
```

How to make my model better on my limited dataset?
